# Generated by Django 5.1.4 on 2025-02-03 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField()),
                ('updated_by_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferences', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField()),
                ('updated_by_id', models.UUIDField()),
                ('material_type', models.CharField(choices=[('CARPET', 'Carpet'), ('BLANKET', 'Blanket'), ('RUG', 'Rug'), ('CURTAIN', 'Curtain'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('WASHING', 'Washing'), ('DRYING', 'Drying'), ('READY', 'Ready'), ('DELIVERED', 'Delivered')], default='RECEIVED', max_length=20)),
                ('dimensions', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('estimated_completion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField()),
                ('updated_by_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('owner_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField()),
                ('updated_by_id', models.UUIDField()),
                ('dimensions', models.JSONField()),
                ('image_url', models.CharField(max_length=255)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('measured_by_id', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='carpet.item')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField()),
                ('updated_by_id', models.UUIDField()),
                ('status', models.CharField(choices=[('NEW', 'New Order'), ('WIP', 'Work in Progress'), ('FINISHED', 'Finished'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to_id', models.UUIDField(null=True)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('estimated_completion', models.DateTimeField(null=True)),
                ('actual_completion', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carpet.client')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpet.workspace')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carpet.order'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField()),
                ('updated_by_id', models.UUIDField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('driver_id', models.UUIDField()),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('customer_signature', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='carpet.order')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpet.workspace'),
        ),
    ]
