# Generated by Django 5.1.4 on 2025-02-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='color',
            field=models.CharField(default='#4F46E5', max_length=7),
        ),
    ]
