# Generated by Django 5.1.4 on 2025-02-04 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpet', '0002_workspace_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField()),
                ('updated_by_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('template_image', models.CharField(max_length=255)),
                ('order_fields', models.JSONField(default=list)),
                ('company_fields', models.JSONField(default=list)),
                ('text_sections', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpet.workspace')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
