# Generated by Django 5.1.4 on 2025-02-04 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpet', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField()),
                ('updated_by_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('working_hours', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpet.workspace')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
