# Generated by Django 5.1.4 on 2025-02-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpet', '0004_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='workspace',
        ),
    ]
