# Generated by Django 5.1.4 on 2025-02-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpet', '0006_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.JSONField(default=dict),
        ),
    ]
